swagger: '2.0'
info:
  version: 0.0.1
  title: Note Server
  license:
    name: MIT
host: '127.0.0.1:3000'
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /notes:
    get:
      summary: List all notes
      operationId: listNotes
      tags:
        - notes
      responses:
        '200':
          description: A list of notes
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /note:
    post:
      summary: Create a note
      operationId: createNote
      tags:
        - notes
      responses:
        '200':
          description: New note is created
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: note
          in: body
          description: Note that we want to create
          schema:
            $ref: '#/definitions/Note'
definitions:
  Note:
    required:
      - tags
      - markdown
    properties:
      markdown:
        type: string
      tags:
        type: array
        items:
         type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
